# Generated by Django 4.1.2 on 2023-06-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_formal_informal_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=1000000)),
                ('user', models.CharField(max_length=1000000)),
                ('voca', models.CharField(max_length=1000000)),
                ('count_var', models.IntegerField()),
            ],
        ),
    ]
