# Generated by Django 4.1.2 on 2023-06-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userformalinformal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformalinformal',
            name='informal_percent_avg',
        ),
    ]
