# Generated by Django 4.1.2 on 2023-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_userformalinformal_informal_percent_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformalinformal',
            name='bebefore_formal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userformalinformal',
            name='before_formal',
            field=models.BooleanField(default=False),
        ),
    ]
