# Generated by Django 4.1.2 on 2023-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userformalinformal_bebefore_formal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformalinformal',
            name='bebefore_informal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userformalinformal',
            name='before_informal',
            field=models.BooleanField(default=False),
        ),
    ]
