# Generated by Django 4.1.2 on 2023-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='formal_warning_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='warning',
            name='voca_warning_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
